# Generated by Django 4.2.7 on 2023-11-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='heat_setting',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cooking_method',
            field=models.CharField(choices=[('baking', 'Baking'), ('grilling', 'Grilling'), ('sauteing', 'Sautéing'), ('boiling', 'Boiling'), ('microwaving', 'Microwaving')], default='baking', max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
