# Generated by Django 4.2.7 on 2023-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_appliance_heat_setting_ingredient_cooking_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='heat_setting',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cooking_method',
            field=models.CharField(choices=[('baking', 'Baking'), ('grilling', 'Grilling'), ('sauteing', 'Sautéing'), ('boiling', 'Boiling'), ('microwaving', 'Microwaving')], max_length=20),
        ),
    ]
