# Generated by Django 4.2.7 on 2023-11-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_alter_appliance_heat_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appliance',
            name='heat_setting',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cooking_method',
            field=models.CharField(choices=[('baking', 'Baking'), ('grilling', 'Grilling'), ('sautéing', 'Sautéing'), ('boiling', 'Boiling'), ('microwaving', 'Microwaving')], max_length=20, null=True),
        ),
    ]
