# Generated by Django 4.2.7 on 2023-11-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_loggeduser_alter_appliance_heat_setting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggeduser',
            old_name='username',
            new_name='user',
        ),
    ]
